name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Analyze
    runs-on: self-hosted

    steps:

      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      # Setup Maven
      - name: Setup Maven
        shell: powershell
        run: |
          echo "MAVEN_HOME=$env:USERPROFILE\maven\apache-maven-3.8.8" >> $env:GITHUB_ENV
          echo "$env:USERPROFILE\maven\apache-maven-3.8.8\bin" >> $env:GITHUB_PATH

      # Build and SonarQube analysis
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B verify sonar:sonar -Dsonar.project.settings=./sonar-project.properties
        shell: cmd
